# This is a list of all permissions found on a reference device (NEXUS 5) on Android 6.0

ALL_ANDROID_PERMISSIONS = {
    'android.intent.category.MASTER_CLEAR.permission.C2D_MESSAGE': ['signature'],
    'android.permission.ACCESS_ALL_DOWNLOADS': ['signature'],
    'android.permission.ACCESS_BLUETOOTH_SHARE': ['signature'],
    'android.permission.ACCESS_CACHE_FILESYSTEM': ['system', 'signature'],
    'android.permission.ACCESS_CHECKIN_PROPERTIES': ['system', 'signature'],
    'android.permission.ACCESS_COARSE_LOCATION': ['dangerous'],
    'android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY': ['signature'],
    'android.permission.ACCESS_DOWNLOAD_MANAGER': ['system', 'signature'],
    'android.permission.ACCESS_DOWNLOAD_MANAGER_ADVANCED': ['system',
                                                            'signature'],
    'android.permission.ACCESS_DRM_CERTIFICATES': ['system', 'signature'],
    'android.permission.ACCESS_FINE_LOCATION': ['dangerous'],
    'android.permission.ACCESS_FM_RADIO': ['system', 'signature'],
    'android.permission.ACCESS_IMS_CALL_SERVICE': ['system', 'signature'],
    'android.permission.ACCESS_INPUT_FLINGER': ['signature'],
    'android.permission.ACCESS_KEYGUARD_SECURE_STORAGE': ['signature'],
    'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS': ['normal'],
    'android.permission.ACCESS_MOCK_LOCATION': ['signature'],
    'android.permission.ACCESS_MTP': ['system', 'signature'],
    'android.permission.ACCESS_NETWORK_CONDITIONS': ['system', 'signature'],
    'android.permission.ACCESS_NETWORK_STATE': ['normal'],
    'android.permission.ACCESS_NOTIFICATIONS': ['system', 'signature'],
    'android.permission.ACCESS_NOTIFICATION_POLICY': ['normal'],
    'android.permission.ACCESS_PDB_STATE': ['signature'],
    'android.permission.ACCESS_SURFACE_FLINGER': ['signature'],
    'android.permission.ACCESS_VOICE_INTERACTION_SERVICE': ['signature'],
    'android.permission.ACCESS_WIFI_STATE': ['normal'],
    'android.permission.ACCESS_WIMAX_STATE': ['normal'],
    'android.permission.ACCOUNT_MANAGER': ['signature'],
    'android.permission.ALLOW_ANY_CODEC_FOR_PLAYBACK': ['system', 'signature'],
    'android.permission.ASEC_ACCESS': ['signature'],
    'android.permission.ASEC_CREATE': ['signature'],
    'android.permission.ASEC_DESTROY': ['signature'],
    'android.permission.ASEC_MOUNT_UNMOUNT': ['signature'],
    'android.permission.ASEC_RENAME': ['signature'],
    'android.permission.BACKUP': ['system', 'signature'],
    'android.permission.BATTERY_STATS': ['development', 'system', 'signature'],
    'android.permission.BIND_ACCESSIBILITY_SERVICE': ['signature'],
    'android.permission.BIND_APPWIDGET': ['system', 'signature'],
    'android.permission.BIND_CARRIER_MESSAGING_SERVICE': ['system', 'signature'],
    'android.permission.BIND_CARRIER_SERVICES': ['system', 'signature'],
    'android.permission.BIND_CHOOSER_TARGET_SERVICE': ['signature'],
    'android.permission.BIND_CONDITION_PROVIDER_SERVICE': ['signature'],
    'android.permission.BIND_CONNECTION_SERVICE': ['system', 'signature'],
    'android.permission.BIND_DEVICE_ADMIN': ['signature'],
    'android.permission.BIND_DIRECTORY_SEARCH': ['system', 'signature'],
    'android.permission.BIND_DREAM_SERVICE': ['signature'],
    'android.permission.BIND_INCALL_SERVICE': ['system', 'signature'],
    'android.permission.BIND_INPUT_METHOD': ['signature'],
    'android.permission.BIND_INTENT_FILTER_VERIFIER': ['signature'],
    'android.permission.BIND_JOB_SERVICE': ['signature'],
    'android.permission.BIND_KEYGUARD_APPWIDGET': ['system', 'signature'],
    'android.permission.BIND_MIDI_DEVICE_SERVICE': ['signature'],
    'android.permission.BIND_NFC_SERVICE': ['signature'],
    'android.permission.BIND_NOTIFICATION_LISTENER_SERVICE': ['signature'],
    'android.permission.BIND_PACKAGE_VERIFIER': ['signature'],
    'android.permission.BIND_PRINT_SERVICE': ['signature'],
    'android.permission.BIND_PRINT_SPOOLER_SERVICE': ['signature'],
    'android.permission.BIND_REMOTEVIEWS': ['system', 'signature'],
    'android.permission.BIND_REMOTE_DISPLAY': ['signature'],
    'android.permission.BIND_ROUTE_PROVIDER': ['signature'],
    'android.permission.BIND_TELECOM_CONNECTION_SERVICE': ['system', 'signature'],
    'android.permission.BIND_TEXT_SERVICE': ['signature'],
    'android.permission.BIND_TRUST_AGENT': ['signature'],
    'android.permission.BIND_TV_INPUT': ['system', 'signature'],
    'android.permission.BIND_VOICE_INTERACTION': ['signature'],
    'android.permission.BIND_VPN_SERVICE': ['signature'],
    'android.permission.BIND_WALLPAPER': ['system', 'signature'],
    'android.permission.BLUETOOTH': ['normal'],
    'android.permission.BLUETOOTH_ADMIN': ['normal'],
    'android.permission.BLUETOOTH_MAP': ['signature'],
    'android.permission.BLUETOOTH_PRIVILEGED': ['system', 'signature'],
    'android.permission.BLUETOOTH_STACK': ['signature'],
    'android.permission.BODY_SENSORS': ['dangerous'],
    'android.permission.BRICK': ['signature'],
    'android.permission.BROADCAST_CALLLOG_INFO': ['system', 'signature'],
    'android.permission.BROADCAST_NETWORK_PRIVILEGED': ['system', 'signature'],
    'android.permission.BROADCAST_PACKAGE_REMOVED': ['signature'],
    'android.permission.BROADCAST_PHONE_ACCOUNT_REGISTRATION': ['system',
                                                                'signature'],
    'android.permission.BROADCAST_SMS': ['signature'],
    'android.permission.BROADCAST_STICKY': ['normal'],
    'android.permission.BROADCAST_WAP_PUSH': ['signature'],
    'android.permission.CALL_PHONE': ['dangerous'],
    'android.permission.CALL_PRIVILEGED': ['system', 'signature'],
    'android.permission.CAMERA': ['dangerous'],
    'android.permission.CAMERA_DISABLE_TRANSMIT_LED': ['system', 'signature'],
    'android.permission.CAMERA_SEND_SYSTEM_EVENTS': ['system', 'signature'],
    'android.permission.CAPTURE_AUDIO_HOTWORD': ['system', 'signature'],
    'android.permission.CAPTURE_AUDIO_OUTPUT': ['system', 'signature'],
    'android.permission.CAPTURE_SECURE_VIDEO_OUTPUT': ['system', 'signature'],
    'android.permission.CAPTURE_TV_INPUT': ['system', 'signature'],
    'android.permission.CAPTURE_VIDEO_OUTPUT': ['system', 'signature'],
    'android.permission.CARRIER_FILTER_SMS': ['system', 'signature'],
    'android.permission.CHANGE_APP_IDLE_STATE': ['signature'],
    'android.permission.CHANGE_BACKGROUND_DATA_SETTING': ['signature'],
    'android.permission.CHANGE_COMPONENT_ENABLED_STATE': ['system', 'signature'],
    'android.permission.CHANGE_CONFIGURATION': ['development',
                                                'system',
                                                'signature'],
    'android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST': ['system',
                                                             'signature'],
    'android.permission.CHANGE_NETWORK_STATE': ['signature'],
    'android.permission.CHANGE_WIFI_MULTICAST_STATE': ['normal'],
    'android.permission.CHANGE_WIFI_STATE': ['normal'],
    'android.permission.CHANGE_WIMAX_STATE': ['normal'],
    'android.permission.CLEAR_APP_CACHE': ['system', 'signature'],
    'android.permission.CLEAR_APP_USER_DATA': ['signature'],
    'android.permission.CONFIGURE_WIFI_DISPLAY': ['signature'],
    'android.permission.CONFIRM_FULL_BACKUP': ['signature'],
    'android.permission.CONNECTIVITY_INTERNAL': ['system', 'signature'],
    'android.permission.CONTROL_INCALL_EXPERIENCE': ['system', 'signature'],
    'android.permission.CONTROL_KEYGUARD': ['signature'],
    'android.permission.CONTROL_LOCATION_UPDATES': ['system', 'signature'],
    'android.permission.CONTROL_VPN': ['system', 'signature'],
    'android.permission.CONTROL_WIFI_DISPLAY': ['signature'],
    'android.permission.COPY_PROTECTED_DATA': ['signature'],
    'android.permission.CRYPT_KEEPER': ['system', 'signature'],
    'android.permission.DELETE_CACHE_FILES': ['system', 'signature'],
    'android.permission.DELETE_PACKAGES': ['system', 'signature'],
    'android.permission.DEVICE_POWER': ['signature'],
    'android.permission.DIAGNOSTIC': ['signature'],
    'android.permission.DISABLE_KEYGUARD': ['normal'],
    'android.permission.DISPATCH_NFC_MESSAGE': ['system', 'signature'],
    'android.permission.DOWNLOAD_CACHE_NON_PURGEABLE': ['system', 'signature'],
    'android.permission.DOWNLOAD_WITHOUT_NOTIFICATION': ['normal'],
    'android.permission.DUMP': ['development', 'system', 'signature'],
    'android.permission.DVB_DEVICE': ['system', 'signature'],
    'android.permission.EXPAND_STATUS_BAR': ['normal'],
    'android.permission.FACTORY_TEST': ['signature'],
    'android.permission.FILTER_EVENTS': ['signature'],
    'android.permission.FLASHLIGHT': ['normal'],
    'android.permission.FORCE_BACK': ['signature'],
    'android.permission.FORCE_STOP_PACKAGES': ['system', 'signature'],
    'android.permission.FRAME_STATS': ['signature'],
    'android.permission.FREEZE_SCREEN': ['signature'],
    'android.permission.GET_ACCOUNTS': ['dangerous'],
    'android.permission.GET_ACCOUNTS_PRIVILEGED': ['system', 'signature'],
    'android.permission.GET_APP_OPS_STATS': ['development',
                                             'system',
                                             'signature'],
    'android.permission.GET_DETAILED_TASKS': ['signature'],
    'android.permission.GET_PACKAGE_IMPORTANCE': ['system', 'signature'],
    'android.permission.GET_PACKAGE_SIZE': ['normal'],
    'android.permission.GET_TASKS': ['normal'],
    'android.permission.GET_TOP_ACTIVITY_INFO': ['signature'],
    'android.permission.GLOBAL_SEARCH': ['system', 'signature'],
    'android.permission.GLOBAL_SEARCH_CONTROL': ['signature'],
    'android.permission.GRANT_RUNTIME_PERMISSIONS': ['signature'],
    'android.permission.HARDWARE_TEST': ['signature'],
    'android.permission.HDMI_CEC': ['system', 'signature'],
    'android.permission.INJECT_EVENTS': ['signature'],
    'android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS': ['signature'],
    'android.permission.INSTALL_LOCATION_PROVIDER': ['system', 'signature'],
    'android.permission.INSTALL_PACKAGES': ['system', 'signature'],
    'android.permission.INTENT_FILTER_VERIFICATION_AGENT': ['system',
                                                            'signature'],
    'android.permission.INTERACT_ACROSS_USERS': ['development',
                                                 'system',
                                                 'signature'],
    'android.permission.INTERACT_ACROSS_USERS_FULL': ['signature'],
    'android.permission.INTERNAL_SYSTEM_WINDOW': ['signature'],
    'android.permission.INTERNET': ['normal'],
    'android.permission.INVOKE_CARRIER_SETUP': ['system', 'signature'],
    'android.permission.KILL_BACKGROUND_PROCESSES': ['normal'],
    'android.permission.KILL_UID': ['signature'],
    'android.permission.LAUNCH_TRUST_AGENT_SETTINGS': ['system', 'signature'],
    'android.permission.LOCAL_MAC_ADDRESS': ['system', 'signature'],
    'android.permission.LOCATION_HARDWARE': ['system', 'signature'],
    'android.permission.LOOP_RADIO': ['system', 'signature'],
    'android.permission.MANAGE_ACTIVITY_STACKS': ['system', 'signature'],
    'android.permission.MANAGE_APP_TOKENS': ['signature'],
    'android.permission.MANAGE_CA_CERTIFICATES': ['system', 'signature'],
    'android.permission.MANAGE_DEVICE_ADMINS': ['system', 'signature'],
    'android.permission.MANAGE_DOCUMENTS': ['signature'],
    'android.permission.MANAGE_FINGERPRINT': ['system', 'signature'],
    'android.permission.MANAGE_MEDIA_PROJECTION': ['signature'],
    'android.permission.MANAGE_NETWORK_POLICY': ['signature'],
    'android.permission.MANAGE_PROFILE_AND_DEVICE_OWNERS': ['signature'],
    'android.permission.MANAGE_USB': ['system', 'signature'],
    'android.permission.MANAGE_USERS': ['system', 'signature'],
    'android.permission.MANAGE_VOICE_KEYPHRASES': ['system', 'signature'],
    'android.permission.MASTER_CLEAR': ['system', 'signature'],
    'android.permission.MEDIA_CONTENT_CONTROL': ['system', 'signature'],
    'android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS': ['system',
                                                             'signature'],
    'android.permission.MODIFY_AUDIO_ROUTING': ['system', 'signature'],
    'android.permission.MODIFY_AUDIO_SETTINGS': ['normal'],
    'android.permission.MODIFY_NETWORK_ACCOUNTING': ['system', 'signature'],
    'android.permission.MODIFY_PARENTAL_CONTROLS': ['system', 'signature'],
    'android.permission.MODIFY_PHONE_STATE': ['system', 'signature'],
    'android.permission.MOUNT_FORMAT_FILESYSTEMS': ['system', 'signature'],
    'android.permission.MOUNT_UNMOUNT_FILESYSTEMS': ['system', 'signature'],
    'android.permission.MOVE_PACKAGE': ['system', 'signature'],
    'android.permission.NET_ADMIN': ['signature'],
    'android.permission.NET_TUNNELING': ['signature'],
    'android.permission.NFC': ['normal'],
    'android.permission.NFC_HANDOVER_STATUS': ['system', 'signature'],
    'android.permission.NOTIFY_PENDING_SYSTEM_UPDATE': ['system', 'signature'],
    'android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS': ['system',
                                                            'signature'],
    'android.permission.OEM_UNLOCK_STATE': ['signature'],
    'android.permission.OVERRIDE_WIFI_CONFIG': ['system', 'signature'],
    'android.permission.PACKAGE_USAGE_STATS': ['development',
                                               'system',
                                               'signature'],
    'android.permission.PACKAGE_VERIFICATION_AGENT': ['system', 'signature'],
    'android.permission.PEERS_MAC_ADDRESS': ['signature'],
    'android.permission.PERFORM_CDMA_PROVISIONING': ['system', 'signature'],
    'android.permission.PERFORM_SIM_ACTIVATION': ['system', 'signature'],
    'android.permission.PERSISTENT_ACTIVITY': ['normal'],
    'android.permission.PROCESS_CALLLOG_INFO': ['system', 'signature'],
    'android.permission.PROCESS_OUTGOING_CALLS': ['dangerous'],
    'android.permission.PROCESS_PHONE_ACCOUNT_REGISTRATION': ['system',
                                                              'signature'],
    'android.permission.PROVIDE_TRUST_AGENT': ['system', 'signature'],
    'android.permission.QUERY_DO_NOT_ASK_CREDENTIALS_ON_BOOT': ['signature'],
    'android.permission.READ_CALENDAR': ['dangerous'],
    'android.permission.READ_CALL_LOG': ['dangerous'],
    'android.permission.READ_CELL_BROADCASTS': ['dangerous'],
    'android.permission.READ_CONTACTS': ['dangerous'],
    'android.permission.READ_DREAM_STATE': ['system', 'signature'],
    'android.permission.READ_EXTERNAL_STORAGE': ['dangerous'],
    'android.permission.READ_FRAME_BUFFER': ['system', 'signature'],
    'android.permission.READ_INPUT_STATE': ['signature'],
    'android.permission.READ_INSTALL_SESSIONS': ['normal'],
    'android.permission.READ_LOGS': ['development', 'system', 'signature'],
    'android.permission.READ_NETWORK_USAGE_HISTORY': ['system', 'signature'],
    'android.permission.READ_PHONE_STATE': ['dangerous'],
    'android.permission.READ_PRECISE_PHONE_STATE': ['system', 'signature'],
    'android.permission.READ_PRIVILEGED_PHONE_STATE': ['system', 'signature'],
    'android.permission.READ_PROFILE': ['normal'],
    'android.permission.READ_SEARCH_INDEXABLES': ['system', 'signature'],
    'android.permission.READ_SMS': ['dangerous'],
    'android.permission.READ_SOCIAL_STREAM': ['normal'],
    'android.permission.READ_SYNC_SETTINGS': ['normal'],
    'android.permission.READ_SYNC_STATS': ['normal'],
    'android.permission.READ_USER_DICTIONARY': ['normal'],
    'android.permission.READ_WIFI_CREDENTIAL': ['system', 'signature'],
    'android.permission.REAL_GET_TASKS': ['system', 'signature'],
    'android.permission.REBOOT': ['system', 'signature'],
    'android.permission.RECEIVE_BLUETOOTH_MAP': ['system', 'signature'],
    'android.permission.RECEIVE_BOOT_COMPLETED': ['normal'],
    'android.permission.RECEIVE_DATA_ACTIVITY_CHANGE': ['system', 'signature'],
    'android.permission.RECEIVE_EMERGENCY_BROADCAST': ['system', 'signature'],
    'android.permission.RECEIVE_MMS': ['dangerous'],
    'android.permission.RECEIVE_SMS': ['dangerous'],
    'android.permission.RECEIVE_STK_COMMANDS': ['system', 'signature'],
    'android.permission.RECEIVE_WAP_PUSH': ['dangerous'],
    'android.permission.RECEIVE_WIFI_CREDENTIAL_CHANGE': ['system', 'signature'],
    'android.permission.RECORD_AUDIO': ['dangerous'],
    'android.permission.RECOVERY': ['system', 'signature'],
    'android.permission.REGISTER_CALL_PROVIDER': ['system', 'signature'],
    'android.permission.REGISTER_CONNECTION_MANAGER': ['system', 'signature'],
    'android.permission.REGISTER_SIM_SUBSCRIPTION': ['system', 'signature'],
    'android.permission.REMOTE_AUDIO_PLAYBACK': ['signature'],
    'android.permission.REMOVE_DRM_CERTIFICATES': ['system', 'signature'],
    'android.permission.REMOVE_TASKS': ['signature'],
    'android.permission.REORDER_TASKS': ['normal'],
    'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': ['normal'],
    'android.permission.REQUEST_INSTALL_PACKAGES': ['normal'],
    'android.permission.RESTART_PACKAGES': ['normal'],
    'android.permission.RETRIEVE_WINDOW_CONTENT': ['system', 'signature'],
    'android.permission.RETRIEVE_WINDOW_TOKEN': ['signature'],
    'android.permission.REVOKE_RUNTIME_PERMISSIONS': ['signature'],
    'android.permission.SCORE_NETWORKS': ['system', 'signature'],
    'android.permission.SEND_CALL_LOG_CHANGE': ['system', 'signature'],
    'android.permission.SEND_DOWNLOAD_COMPLETED_INTENTS': ['signature'],
    'android.permission.SEND_RESPOND_VIA_MESSAGE': ['system', 'signature'],
    'android.permission.SEND_SMS': ['dangerous'],
    'android.permission.SERIAL_PORT': ['system', 'signature'],
    'android.permission.SET_ACTIVITY_WATCHER': ['signature'],
    'android.permission.SET_ALWAYS_FINISH': ['development',
                                             'system',
                                             'signature'],
    'android.permission.SET_ANIMATION_SCALE': ['development',
                                               'system',
                                               'signature'],
    'android.permission.SET_DEBUG_APP': ['development', 'system', 'signature'],
    'android.permission.SET_INPUT_CALIBRATION': ['signature'],
    'android.permission.SET_KEYBOARD_LAYOUT': ['signature'],
    'android.permission.SET_ORIENTATION': ['signature'],
    'android.permission.SET_POINTER_SPEED': ['signature'],
    'android.permission.SET_PREFERRED_APPLICATIONS': ['signature'],
    'android.permission.SET_PROCESS_LIMIT': ['development',
                                             'system',
                                             'signature'],
    'android.permission.SET_SCREEN_COMPATIBILITY': ['signature'],
    'android.permission.SET_TIME': ['system', 'signature'],
    'android.permission.SET_TIME_ZONE': ['normal'],
    'android.permission.SET_WALLPAPER': ['normal'],
    'android.permission.SET_WALLPAPER_COMPONENT': ['system', 'signature'],
    'android.permission.SET_WALLPAPER_HINTS': ['normal'],
    'android.permission.SHUTDOWN': ['system', 'signature'],
    'android.permission.SIGNAL_PERSISTENT_PROCESSES': ['development',
                                                       'system',
                                                       'signature'],
    'android.permission.START_ANY_ACTIVITY': ['signature'],
    'android.permission.START_PRINT_SERVICE_CONFIG_ACTIVITY': ['signature'],
    'android.permission.START_TASKS_FROM_RECENTS': ['system', 'signature'],
    'android.permission.STATUS_BAR': ['system', 'signature'],
    'android.permission.STATUS_BAR_SERVICE': ['signature'],
    'android.permission.STOP_APP_SWITCHES': ['system', 'signature'],
    'android.permission.SYSTEM_ALERT_WINDOW': ['signature'],
    'android.permission.TEMPORARY_ENABLE_ACCESSIBILITY': ['signature'],
    'android.permission.TRANSMIT_IR': ['normal'],
    'android.permission.TRUST_LISTENER': ['signature'],
    'android.permission.TV_INPUT_HARDWARE': ['system', 'signature'],
    'android.permission.UPDATE_APP_OPS_STATS': ['system', 'signature'],
    'android.permission.UPDATE_CONFIG': ['system', 'signature'],
    'android.permission.UPDATE_DEVICE_STATS': ['system', 'signature'],
    'android.permission.UPDATE_LOCK': ['system', 'signature'],
    'android.permission.USER_ACTIVITY': ['system', 'signature'],
    'android.permission.USE_FINGERPRINT': ['normal'],
    'android.permission.USE_SIP': ['dangerous'],
    'android.permission.VIBRATE': ['normal'],
    'android.permission.WAKE_LOCK': ['normal'],
    'android.permission.WRITE_APN_SETTINGS': ['system', 'signature'],
    'android.permission.WRITE_CALENDAR': ['dangerous'],
    'android.permission.WRITE_CALL_LOG': ['dangerous'],
    'android.permission.WRITE_CONTACTS': ['dangerous'],
    'android.permission.WRITE_DREAM_STATE': ['system', 'signature'],
    'android.permission.WRITE_EXTERNAL_STORAGE': ['dangerous'],
    'android.permission.WRITE_GSERVICES': ['system', 'signature'],
    'android.permission.WRITE_MEDIA_STORAGE': ['system', 'signature'],
    'android.permission.WRITE_PROFILE': ['normal'],
    'android.permission.WRITE_SECURE_SETTINGS': ['development',
                                                 'system',
                                                 'signature'],
    'android.permission.WRITE_SETTINGS': ['signature'],
    'android.permission.WRITE_SOCIAL_STREAM': ['normal'],
    'android.permission.WRITE_SYNC_SETTINGS': ['normal'],
    'android.permission.WRITE_USER_DICTIONARY': ['normal'],
    'android.server.checkin.CHECKIN.permission.C2D_MESSAGE': ['signature'],
    'com.android.alarm.permission.SET_ALARM': ['normal'],
    'com.android.certinstaller.INSTALL_AS_USER': ['signature'],
    'com.android.chrome.TOS_ACKED': ['system', 'signature'],
    'com.android.chrome.permission.C2D_MESSAGE': ['signature'],
    'com.android.chrome.permission.CHILD_SERVICE': ['signature'],
    'com.android.chrome.permission.DEBUG': ['signature'],
    'com.android.chrome.permission.READ_WRITE_BOOKMARK_FOLDERS': ['system',
                                                                  'signature'],
    'com.android.gallery3d.filtershow.permission.READ': ['signature'],
    'com.android.gallery3d.filtershow.permission.WRITE': ['signature'],
    'com.android.launcher.permission.INSTALL_SHORTCUT': ['normal'],
    'com.android.launcher.permission.UNINSTALL_SHORTCUT': ['normal'],
    'com.android.permission.WHITELIST_BLUETOOTH_DEVICE': ['signature'],
    'com.android.printspooler.permission.ACCESS_ALL_PRINT_JOBS': ['signature'],
    'com.android.systemui.permission.SELF': ['signature'],
    'com.android.vending.BILLING': ['normal'],
    'com.android.vending.CHECK_LICENSE': ['normal'],
    'com.android.vending.INTENT_VENDING_ONLY': ['signature'],
    'com.android.vending.TOS_ACKED': ['system', 'signature'],
    'com.android.vending.billing.ADD_CREDIT_CARD': ['system', 'signature'],
    'com.android.vending.billing.BILLING_ACCOUNT_SERVICE': ['system',
                                                            'signature'],
    'com.android.vending.billing.IN_APP_NOTIFY.permission.C2D_MESSAGE': ['signature'],
    'com.android.vending.permission.C2D_MESSAGE': ['signature'],
    'com.android.vending.setup.PLAY_SETUP_SERVICE': ['system', 'signature'],
    'com.android.voicemail.permission.ADD_VOICEMAIL': ['dangerous'],
    'com.android.voicemail.permission.READ_VOICEMAIL': ['system', 'signature'],
    'com.android.voicemail.permission.WRITE_VOICEMAIL': ['system', 'signature'],
    'com.domobile.applock.PERMISSON_STOP_WATCHDOG_AFTER_SCREEN_OFF': ['signature'],
    'com.domobile.applock.SEND_CALL_STATE_BROADCAST': ['signature'],
    'com.google.android.apps.cloudprint.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.apps.docs.editors.kix.permission.READ_MY_DATA': ['system',
                                                                         'signature'],
    'com.google.android.apps.docs.editors.kix.permission.SYNC_STATUS': ['normal'],
    'com.google.android.apps.docs.editors.punch.permission.READ_MY_DATA': ['system',
                                                                           'signature'],
    'com.google.android.apps.docs.editors.punch.permission.SYNC_STATUS': ['normal'],
    'com.google.android.apps.docs.editors.trix.permission.READ_MY_DATA': ['system',
                                                                          'signature'],
    'com.google.android.apps.docs.editors.trix.permission.SYNC_STATUS': ['normal'],
    'com.google.android.apps.docs.permission.READ_MY_DATA': ['system',
                                                             'signature'],
    'com.google.android.apps.docs.permission.SYNC_STATUS': ['normal'],
    'com.google.android.apps.enterprise.dmagent.permission.AutoRegisterPermission': ['system',
                                                                                     'signature'],
    'com.google.android.apps.enterprise.dmagent.permission.AutoSyncPermission': ['system',
                                                                                 'signature'],
    'com.google.android.apps.enterprise.dmagent.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.apps.enterprise.dmagent.permission.InvokeDMServicePermission': ['signature'],
    'com.google.android.apps.enterprise.dmagent.permission.NotificationBroadcastReceiverPermission': ['system',
                                                                                                      'signature'],
    'com.google.android.apps.fitness.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.apps.gcs.RECEIVE_GCS_STATE': ['system', 'signature'],
    'com.google.android.apps.genie.geniewidget.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.apps.magazines.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.apps.maps.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.apps.maps.permission.PREFETCH': ['signature'],
    'com.google.android.apps.now.CURRENT_ACCOUNT_ACCESS': ['signature'],
    'com.google.android.apps.now.OPT_IN_WIZARD': ['system', 'signature'],
    'com.google.android.apps.photos.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.apps.photos.permission.GOOGLE_PHOTOS': ['dangerous'],
    'com.google.android.apps.photos.permission.GOOGLE_PHOTOS_PROVIDER': ['dangerous'],
    'com.google.android.apps.plus.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.apps.plus.permission.MAPS_RECEIVE': ['signature'],
    'com.google.android.apps.plus.permission.PICASA_STORE': ['dangerous'],
    'com.google.android.apps.wallet.permission.WALLET_INTERNAL': ['signature'],
    'com.google.android.apps.walletnfcrel.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.c2dm.permission.RECEIVE': ['normal'],
    'com.google.android.c2dm.permission.SEND': ['system', 'signature'],
    'com.google.android.calendar.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.calendar.permission.READ_OOBE': ['signature'],
    'com.google.android.finsky.permission.GEARHEAD_SERVICE': ['system',
                                                              'signature'],
    'com.google.android.gallery3d.permission.GALLERY_PROVIDER': ['signature'],
    'com.google.android.gm.email.permission.ACCESS_PROVIDER': ['signature'],
    'com.google.android.gm.email.permission.READ_ATTACHMENT': ['signature'],
    'com.google.android.gm.email.permission.UPDATE_AUTH_NOTIFICATION': ['signature'],
    'com.google.android.gm.permission.AUTO_SEND': ['signature'],
    'com.google.android.gm.permission.READ_CONTENT_PROVIDER': ['dangerous'],
    'com.google.android.gm.permission.READ_GMAIL': ['signature'],
    'com.google.android.gm.permission.WRITE_GMAIL': ['signature'],
    'com.google.android.gms.DRIVE': ['signature'],
    'com.google.android.gms.auth.permission.FACE_UNLOCK': ['signature'],
    'com.google.android.gms.auth.permission.GOOGLE_ACCOUNT_CHANGE': ['signature'],
    'com.google.android.gms.auth.permission.POST_SIGN_IN_ACCOUNT': ['signature'],
    'com.google.android.gms.chromesync.permission.CONTENT_PROVIDER_ACCESS': ['signature'],
    'com.google.android.gms.cloudsave.BIND_EVENT_BROADCAST': ['system',
                                                              'signature'],
    'com.google.android.gms.permission.ACTIVITY_RECOGNITION': ['normal'],
    'com.google.android.gms.permission.AD_ID_NOTIFICATION': ['normal'],
    'com.google.android.gms.permission.BIND_NETWORK_TASK_SERVICE': ['signature'],
    'com.google.android.gms.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.gms.permission.CAR': ['signature'],
    'com.google.android.gms.permission.CAR_FUEL': ['dangerous'],
    'com.google.android.gms.permission.CAR_MILEAGE': ['dangerous'],
    'com.google.android.gms.permission.CAR_SPEED': ['dangerous'],
    'com.google.android.gms.permission.CAR_VENDOR_EXTENSION': ['dangerous'],
    'com.google.android.gms.permission.CHECKIN_NOW': ['signature'],
    'com.google.android.gms.permission.GAMES_DEBUG_SETTINGS': ['signature'],
    'com.google.android.gms.permission.INTERNAL_BROADCAST': ['signature'],
    'com.google.android.gms.trustagent.framework.model.DATA_ACCESS': ['signature'],
    'com.google.android.gms.trustagent.framework.model.DATA_CHANGE_NOTIFICATION': ['signature'],
    'com.google.android.gms.trustagent.permission.TRUSTAGENT_STATE': ['signature'],
    'com.google.android.googleapps.permission.ACCESS_GOOGLE_PASSWORD': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.ALL_SERVICES': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.OTHER_SERVICES': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.YouTubeUser': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.adsense': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.adwords': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.ah': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.android': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.androidsecure': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.blogger': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.cl': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.cp': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.dodgeball': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.finance': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.gbase': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.grandcentral': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.groups2': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.health': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.ig': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.jotspot': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.knol': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.lh2': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.local': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.mail': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.mobile': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.news': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.notebook': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.orkut': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.print': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.sierra': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.sierraqa': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.sierrasandbox': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.sitemaps': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.speech': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.speechpersonalization': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.talk': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.wifi': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.wise': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.writely': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_AUTH.youtube': ['signature'],
    'com.google.android.googleapps.permission.GOOGLE_MAIL_SWITCH': ['signature'],
    'com.google.android.googlequicksearchbox.LAUNCH_FROM_DSP_HOTWORD': ['system',
                                                                        'signature'],
    'com.google.android.googlequicksearchbox.LAUNCH_WITH_RECORDED_AUDIO': ['system',
                                                                           'signature'],
    'com.google.android.googlequicksearchbox.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.googlequicksearchbox.permission.FINISH_GEL_ACTIVITY': ['signature'],
    'com.google.android.googlequicksearchbox.permission.FLUSH_LOGS': ['signature'],
    'com.google.android.googlequicksearchbox.permission.PAUSE_HOTWORD': ['system',
                                                                         'signature'],
    'com.google.android.gsf.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.gsf.permission.CONNECTION': ['signature'],
    'com.google.android.gsf.subscribedfeeds.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.gtalkservice.permission.GTALK_SERVICE': ['signature'],
    'com.google.android.gtalkservice.permission.SEND_HEARTBEAT': ['system',
                                                                  'signature'],
    'com.google.android.hangouts.START_HANGOUT': ['signature'],
    'com.google.android.launcher.permission.CONTENT_REDIRECT': ['signature'],
    'com.google.android.launcher.permission.READ_SETTINGS': ['normal'],
    'com.google.android.launcher.permission.RECEIVE_FIRST_LOAD_BROADCAST': ['system',
                                                                            'signature'],
    'com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS': ['signature'],
    'com.google.android.launcher.permission.WRITE_SETTINGS': ['system',
                                                              'signature'],
    'com.google.android.marvin.feedback.permission.TALKBACK': ['signature'],
    'com.google.android.marvin.talkback.permission.LABELING': ['signature'],
    'com.google.android.music.store.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.onetimeinitializer.permission.ONE_TIME_INITIALIZED': ['signature'],
    'com.google.android.partnersetup.permission.ACCESS_PROVIDER': ['signature'],
    'com.google.android.partnersetup.permission.UPDATE_CLIENT_ID': ['system',
                                                                    'signature'],
    'com.google.android.permission.BROADCAST_DATA_MESSAGE': ['system',
                                                             'signature'],
    'com.google.android.providers.gsf.permission.READ_GSERVICES': ['normal'],
    'com.google.android.providers.gsf.permission.WRITE_GSERVICES': ['system',
                                                                    'signature'],
    'com.google.android.providers.settings.permission.READ_GSETTINGS': ['signature'],
    'com.google.android.providers.settings.permission.WRITE_GSETTINGS': ['signature'],
    'com.google.android.providers.talk.permission.READ_ONLY': ['dangerous'],
    'com.google.android.providers.talk.permission.WRITE_ONLY': ['dangerous'],
    'com.google.android.talk.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.videos.permission.C2D_MESSAGE': ['signature'],
    'com.google.android.videos.permission.INVALIDATE_AUTH_TOKENS': ['signature'],
    'com.google.android.voicesearch.AUDIO_FILE_ACCESS': ['signature'],
    'com.google.android.xmpp.permission.BROADCAST': ['system', 'signature'],
    'com.google.android.xmpp.permission.SEND_RECEIVE': ['signature'],
    'com.google.android.xmpp.permission.USE_XMPP_ENDPOINT': ['signature'],
    'com.google.android.xmpp.permission.XMPP_ENDPOINT_BROADCAST': ['system',
                                                                   'signature'],
    'com.google.android.youtube.permission.C2D_MESSAGE': ['signature'],
    'com.google.googlenav.friend.permission.OPT_IN': ['signature'],
    'com.lge.permission.SPRINTHIDDEN': ['system', 'signature'],
    'com.qualcomm.permission.USE_QCRIL_MSG_TUNNEL': ['system', 'signature']}

ALL_FEATURES = [
    'android.hardware.nfc',
    'android.hardware.camera.capability.manual_post_processing',
    'android.hardware.ethernet',
    'android.hardware.camera.any',
    'android.hardware.audio.low_latency',
    'android.software.input_methods',
    'android.hardware.sensor.hifi_sensors',
    'android.hardware.camera.capability.raw',
    'android.hardware.bluetooth_le',
    'android.hardware.faketouch',
    'android.software.backup',
    'android.hardware.camera.front',
    'android.software.app_widgets',
    'android.hardware.wifi.direct',
    'android.software.live_wallpaper',
    'android.hardware.telephony',
    'com.google.android.feature.EXCHANGE_6_2',
    'android.hardware.telephony.gsm',
    'android.hardware.camera.flash',
    'com.nxp.mifare',
    'android.hardware.sensor.light',
    'android.hardware.location.gps',
    'android.hardware.usb.accessory',
    'android.software.webview',
    'android.software.sip.voip',
    'android.hardware.microphone',
    'android.hardware.fingerprint',
    'android.hardware.location.network',
    'android.software.midi',
    'android.hardware.touchscreen.multitouch',
    'android.software.voice_recognizers',
    'android.hardware.touchscreen.multitouch.jazzhand',
    'android.hardware.sensor.barometer',
    'android.hardware.audio.output',
    'com.google.android.feature.GOOGLE_EXPERIENCE',
    'android.hardware.camera.capability.manual_sensor',
    'com.google.android.feature.GOOGLE_BUILD',
    'android.hardware.sensor.stepcounter',
    'android.hardware.touchscreen',
    'android.hardware.bluetooth',
    'android.hardware.wifi',
    'android.software.sip',
    'android.hardware.screen.portrait',
    'android.hardware.camera.level.full',
    'android.hardware.nfc.hce',
    'android.hardware.sensor.proximity',
    'android.hardware.sensor.compass',
    'android.hardware.telephony.cdma',
    'android.hardware.camera',
    'android.hardware.audio.pro',
    'android.software.device_admin',
    'android.software.print',
    'android.hardware.location',
    'android.software.home_screen',
    'android.hardware.touchscreen.multitouch.distinct',
    'android.hardware.sensor.stepdetector',
    'android.hardware.sensor.gyroscope',
    'android.hardware.camera.autofocus',
    'android.software.managed_users',
    'android.hardware.sensor.accelerometer',
    'android.hardware.screen.landscape',
    'android.hardware.usb.host',
    'android.software.connectionservice']

SHARED_LIBRARIES = [
    "android.test.runner",
    "com.android.future.usb.accessory",
    "com.android.lge.lgsvcitems",
    "com.android.location.provider",
    "com.android.media.remotedisplay",
    "com.android.mediadrm.signer",
    "com.google.android.camera2",
    "com.google.android.dialer.support",
    "com.google.android.gms",
    "com.google.android.maps",
    "com.google.android.media.effects",
    "com.google.widevine.software.drm",
    "com.qualcomm.qcrilhook",
    "javax.obex",
    "org.apache.http.legacy"
]

ISO_LOCALES = [
    "AF",
    "AX",
    "AL",
    "DZ",
    "AS",
    "AD",
    "AO",
    "AI",
    "AQ",
    "AG",
    "AR",
    "AM",
    "AW",
    "AU",
    "AT",
    "AZ",
    "BS",
    "BH",
    "BD",
    "BB",
    "BY",
    "BE",
    "BZ",
    "BJ",
    "BM",
    "BT",
    "BO",
    "BQ",
    "BA",
    "BW",
    "BV",
    "BR",
    "IO",
    "BN",
    "BG",
    "BF",
    "BI",
    "CV",
    "KH",
    "CM",
    "CA",
    "KY",
    "CF",
    "TD",
    "CL",
    "CN",
    "CX",
    "CC",
    "CO",
    "KM",
    "CG",
    "CD",
    "CK",
    "CR",
    "CI",
    "HR",
    "CU",
    "CW",
    "CY",
    "CZ",
    "DK",
    "DJ",
    "DM",
    "DO",
    "EC",
    "EG",
    "SV",
    "GQ",
    "ER",
    "EE",
    "ET",
    "FK",
    "FO",
    "FJ",
    "FI",
    "FR",
    "GF",
    "PF",
    "TF",
    "GA",
    "GM",
    "GE",
    "DE",
    "GH",
    "GI",
    "GR",
    "GL",
    "GD",
    "GP",
    "GU",
    "GT",
    "GG",
    "GN",
    "GW",
    "GY",
    "HT",
    "HM",
    "VA",
    "HN",
    "HK",
    "HU",
    "IS",
    "IN",
    "ID",
    "IR",
    "IQ",
    "IE",
    "IM",
    "IL",
    "IT",
    "JM",
    "JP",
    "JE",
    "JO",
    "KZ",
    "KE",
    "KI",
    "KP",
    "KR",
    "KW",
    "KG",
    "LA",
    "LV",
    "LB",
    "LS",
    "LR",
    "LY",
    "LI",
    "LT",
    "LU",
    "MO",
    "MK",
    "MG",
    "MW",
    "MY",
    "MV",
    "ML",
    "MT",
    "MH",
    "MQ",
    "MR",
    "MU",
    "YT",
    "MX",
    "FM",
    "MD",
    "MC",
    "MN",
    "ME",
    "MS",
    "MA",
    "MZ",
    "MM",
    "NA",
    "NR",
    "NP",
    "NL",
    "NC",
    "NZ",
    "NI",
    "NE",
    "NG",
    "NU",
    "NF",
    "MP",
    "NO",
    "OM",
    "PK",
    "PW",
    "PS",
    "PA",
    "PG",
    "PY",
    "PE",
    "PH",
    "PN",
    "PL",
    "PT",
    "PR",
    "QA",
    "RE",
    "RO",
    "RU",
    "RW",
    "BL",
    "SH",
    "KN",
    "LC",
    "MF",
    "PM",
    "VC",
    "WS",
    "SM",
    "ST",
    "SA",
    "SN",
    "RS",
    "SC",
    "SL",
    "SG",
    "SX",
    "SK",
    "SI",
    "SB",
    "SO",
    "ZA",
    "GS",
    "SS",
    "ES",
    "LK",
    "SD",
    "SR",
    "SJ",
    "SZ",
    "SE",
    "CH",
    "SY",
    "TW",
    "TJ",
    "TZ",
    "TH",
    "TL",
    "TG",
    "TK",
    "TO",
    "TT",
    "TN",
    "TR",
    "TM",
    "TC",
    "TV",
    "UG",
    "UA",
    "AE",
    "GB",
    "US",
    "UM",
    "UY",
    "UZ",
    "VU",
    "VE",
    "VN",
    "VG",
    "VI",
    "WF",
    "EH",
    "YE",
    "ZM",
    "ZW"
]