#!/usr/local/bin/perl -w -I..

use PGP::PublicKeyRing;


my $pkr = restoreFromFile PGP::PublicKeyRing "pubring.pgp";
print $pkr->asString();

print "-----\n";

# my $pk = $pkr->getKey('joe')->publicKey();
# print $pk->asString();

print "-----\n";

foreach (@{$pkr->ids()})
{
	my $id = $_->[0]->[0];
	my $key = $_->[1]->key();

	print "$id\n";
}

