#!/usr/local/bin/perl -w -I.

use Crypt::SHA;
use Crypt::MD5;

my $hash = Crypt::MD5->hash("ABC");
my $hash2 = Crypt::SHA->hash("ABC");

print "$hash\n$hash2\n";
print "ok 1\n" if ($hash eq $hash2);
print "ok 2\n" if ($hash == $hash2);
print "ok 3\n" unless ($hash ne $hash2);
print "ok 4\n" unless ($hash != $hash2);
