#!/usr/local/bin/perl -w -I.


use Math::MPI;

my $i = new Math::MPI 1234;
# my $j = new Math::MPI 2;
my $j = $i;

print $i->saveAsInt(), "\n";
print $i, "\n";

print "$i, $j\n";

$i++; $j++;
$i++; $j++;
$i++; $j++;
print "$i, $j\n";

$i++; $j--;
print "$i, $j\n";
$i++; $j--;
print "$i, $j\n";
$i++; $j--;
print "$i, $j\n";

print $i + $j, "\n";

print $i->saveAsInt(), "\n";
print $j->saveAsInt(), "\n";

my $b = restoreWithoutHdr Math::MPI pack("H*", "dc9925e1f1d41131acf23c86811eab4bc7b8ce1e9cbcb00aa2c09c3bf05067c1");
print ref($b), "\n";

my $c = $b;
$c++;


my $zero = $c->new();
my $one = $c->new();

print ref($c), "\n";
print ref($zero), "\n";

$one++;
print "B = $b\n";
print "C = $c\n";
print "Zero = $zero\n";
print "One = $one\n";
print "Zero = $zero\n";
print "One = $one\n";

print "B = $b\n";
print "C = $c\n";
