#!/usr/local/bin/perl -w -I.

use Math::PseudoRandomStream;

$prsg = new Math::PseudoRandomStream pack("H*", "0123456789ABCDEF0123456789ABCDEF01234567");

print "1 ";
(unpack("H*", $prsg->read(20)) eq "c091a2b3c4d5e6f78091a2b3c4d5e6f7c091a2b3") || print "not ";
print "ok\n";

print "2 ";
(unpack("H*", $prsg->read(20)) eq "a048d159e26af37bc048d159e26af37ba048d159") || print "not ";
print "ok\n";

print "3 ";
(unpack("H*", $prsg->read(20)) eq "902468acf13579bde02468acf13579bd902468ac") || print "not ";
print "ok\n";

print "4 ";
$prsg->skip(2000);
(unpack("H*", $prsg->read(20)) eq "ce17614bad2da758f2c1b2e7d4812345227b74f4") || print "not ";
print "ok\n";

print "5 ";
$prsg->skip(2000000);
(unpack("H*", $prsg->read(20)) eq "b0d927dd87d8b63859643d40ea736bb6379656b1") || print "not ";
print "ok\n";
