/*
 * This software may be freely distributed an modified without any restrictions
 * from the author.
 * Additional restrictions due to national laws governing the use, import or
 * export of cryptographic software is the responsibility of the software user,
 * importer or exporter to follow.
 *
 *					     _
 *					Stig Ostholm
 *					Department of Computer Engineering
 *					Chalmers University of Technology
 */

/*
 * 
 */

#define DES_BITS 64

#define DES_ITERATIONS 16

#define DES_L_BITS 32
#define DES_R_BITS 32

#define DES_KS_BITS 48

#define DES_C_BITS 28
#define DES_D_BITS 28
